# Site settings | 网站设置
title: yangmingsen
SEOTitle: yangmingsen的博客 | yangmingsen
header-img: img/home-bg-he.png
email: yangmingsen16@outlook.com
description: "yangmingsen的博客"
keyword: "yangmingsen, yangmingsen的博客, yangmingsen, yangmingsen, yangmingsen"
url: "http://yangmingsen.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/yangmingsen/yangmingsen.github.io.git" #code repository | 代码仓库


# Sidebar settings | 侧边栏设置
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "就算这样,也要笑着去努力啊!"
sidebar-avatar: /img/head.jpg      # 头像





# SNS settings | 社交网络设置
facebook_username: yangmingsen
github_username: yangmingsen
zhihu_username: yangmingsen
csdn_username: yangmingsen




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
# 转换时排除某些文件夹或文件。被排除的文件或文件夹的路径是相对于网站源码目录的，源码目录以外不受影响。
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

Regeneration: true    # 允许文件修改时自动重新生成网站。





# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Gitalk
gitalk:
  enable: true    # 是否开启Gitalk评论
  clientID: 1675c22923c74e399e8e                            #生成的clientID
  clientSecret: 9d7a97297ac73a483211f95a15197d8f53039a80    #生成的clientSecret
  repo: yangmingsen.github.io    #仓库名称
  owner: yangmingsen    # github用户名
  admin: yangmingsen
  distractionFreeMode: true # 是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68


# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "GitHub·yangmingsen",
        href: "http://yangmingsen.github.io"
    },{
        title: "CSDN·yangmingsen",
        href: "https://blog.csdn.net/yangmingsen"
    },{
        title: "知乎·yangmingsen",
        href: "https://www.zhihu.com/people/yangmingsen"
    },{
        title: "GitBook·yangmingsen",
        href: "https://legacy.gitbook.com/@yangmingsen"
    }
]
